---
name: changelog and linters

on: [workflow_call] # allow this workflow to be called from other workflows

jobs:
  linters:
    name: Run custom linters
    runs-on: ubuntu-latest
    steps:
      - name: Run linters
        run: CI=true make linters
